_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_PBresnet_backbone"
  RPN:
    HEAD_NAME: "PBRPNHead"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  WEIGHTS: "./output/voc[1,15]/model_final.pth"
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ('voc[20,20]_train', )
  TEST: ('voc_2007_test', )
SOLVER:
  OPTIM: "Adam"
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  MASK_LR: 0.00001
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
  CHECKPOINT_PERIOD: 1000
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./output/pb[roi_heads]19+1"
